apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  metric:
    enabled: true
    rules:
    - name: dapr_runtime_service_invocation_req_recv_total
      labels:
      - name: method
        regex:
          "api/Receive/": "api/Receive/.+"
    - name: dapr_runtime_service_invocation_res_sent_total
      labels:
      - name: method
        regex:
          "api/Receive/": "api/Receive/.+"